apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: default
spec:
  securityContext:
    fsGroup: 1000
  serviceAccountName: jenkins-sa
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
      - mountPath: /home/jenkins/agent/.m2
        name: m2-home
  restartPolicy: Never
  volumes:
  - name: m2-home
    persistentVolumeClaim:
      claimName: jenkins-pv-claim-m2